  # for setting paths
  computer: 2020laptop

  # data setup
  validation_split: 0.2

  # hyperparameters
  batch_size: 256
  edge_size: 48
  activation_function: relu

  # training
  epochs: 5
  learning_rate: 1.0e-3
  optimizer: adam

  # experiment parameters
  trial_label: edge48batch256
  plot_history: False
  save_model: True
  verbose: True