  # for setting paths
  computer: 2020laptop

  # data setup
  validation_split: 0.2
  seed: 123
  shuffle: True

  # hyperparameters
  batch_size: 256

  # training
  epochs: 10
  learning_rate: 1.0e-3
  optimizer: adam

  # experiment parameters
  trial_label: trainedOn100
  plot_history: False
  save_model: False
  verbose: False