  # for setting paths
  computer: 2020laptop

  # data setup
  validation_split: 0.2
  seed: 123

  # hyperparameters
  batch_size: 512
  edge_size: 64
  activation_function: relu

  # training
  epochs: 5
  learning_rate: 1.0e-3
  optimizer: adam

  # experiment parameters
  trial_label: edge64batch512
  plot_history: False
  save_model: True
  verbose: True